# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-07 19:09
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2016, 11, 7, 19, 9, 56, 879060, tzinfo=utc)),
        ),
    ]
