# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-29 17:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20161214_1929'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='hru',
            field=models.CharField(default='', max_length=255, unique=True),
            preserve_default=False,
        ),
    ]
