# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-02-12 09:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_post_hru'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='hru',
            new_name='slug',
        ),
    ]
