# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-03-11 08:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20170212_0900'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='short_content',
            field=models.CharField(default='Default short content', max_length=255),
            preserve_default=False,
        ),
    ]
