# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-03-11 08:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_post_short_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='short_content',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
