# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-06 07:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_post_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='post',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.Post'),
            preserve_default=False,
        ),
    ]
